"""empty message

Revision ID: 2920dcb8ce63
Revises: 
Create Date: 2024-08-28 23:05:10.135042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2920dcb8ce63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Publicaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Publicaciones',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Publicaciones', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
